packages:
  - packages/*
  - profiles/*

allowBuilds:
  '@deepseek-ai/dsh-subprocess-local': true
  '@google/genai': true
  cpu-features: true
  koffi: true
  node-pty: true
  protobufjs: true
  ssh2: true

nodeLinker: hoisted
