import { defineConfig } from 'tsdown'

const EXTERNAL_CLIENT = [
  'react',
  'react/jsx-runtime',
  '@deepseek-ai/cordis',
  '@deepseek-ai/dsh-client-ui-slots',
  '@deepseek-ai/dsh-client-runtime',
  '@deepseek-ai/dsh-client-runtime/client',
  '@deepseek-ai/dsh-client-ui-settings',
  '@deepseek-ai/dsh-client-ui-settings/client',
  '@deepseek-ai/dsh-client-ui-workspace',
  '@deepseek-ai/dsh-client-ui-workspace/client',
]

const BUNDLE_ID = '@artenx/dshb'

const serverEntries = {
  index: 'src/index.ts',
  'auth/index': 'src/auth/index.ts',
  'auth/startup': 'src/auth/startup.ts',
  'auth/decorate-webserver': 'src/auth/decorate-webserver.ts',
  'auth/loopback': 'src/auth/loopback.ts',
  'auth/loopback-compat': 'src/auth/loopback-compat.ts',
  'auth/routes': 'src/auth/routes.ts',
  'auth/credentials': 'src/auth/credentials.ts',
  'auth/session': 'src/auth/session.ts',
  'auth/ratelimit': 'src/auth/ratelimit.ts',
  'auth/gate': 'src/auth/gate.ts',
  'auth/login-page': 'src/auth/login-page.ts',
  'auth/webserver': 'src/auth/webserver.ts',
  'core/index': 'src/core/index.ts',
  'core/node-registry': 'src/core/node-registry.ts',
  'core/routes': 'src/core/routes.ts',
  'core/test': 'src/core/test.ts',
  'core/ssh-config': 'src/core/ssh-config.ts',
  'core/known-hosts': 'src/core/known-hosts.ts',
  'core/workspace-bindings': 'src/core/workspace-bindings.ts',
  'core/workspaces': 'src/core/workspaces.ts',
  'core/audit': 'src/core/audit.ts',
  'router/index': 'src/router/index.ts',
  'router/resolve': 'src/router/resolve.ts',
  'router/types': 'src/router/types.ts',
  'router/decorate-fs': 'src/router/decorate-fs.ts',
  'router/decorate-subprocess': 'src/router/decorate-subprocess.ts',
  'router/decorate-shell': 'src/router/decorate-shell.ts',
  'router/router-fs': 'src/router/router-fs.ts',
  'router/router-subprocess': 'src/router/router-subprocess.ts',
  'router/router-shell': 'src/router/router-shell.ts',
  'exec-ssh/index': 'src/exec-ssh/index.ts',
  'exec-ssh/connection': 'src/exec-ssh/connection.ts',
  'exec-ssh/connection-pool': 'src/exec-ssh/connection-pool.ts',
  'exec-ssh/env-scrub': 'src/exec-ssh/env-scrub.ts',
  'exec-ssh/runner': 'src/exec-ssh/runner.ts',
  'exec-ssh/executor': 'src/exec-ssh/executor.ts',
  'exec-ssh/fs-provider': 'src/exec-ssh/fs-provider.ts',
  'exec-ssh/process-provider': 'src/exec-ssh/process-provider.ts',
  'exec-ssh/world': 'src/exec-ssh/world.ts',
  'exec-docker/index': 'src/exec-docker/index.ts',
  'exec-docker/docker-client': 'src/exec-docker/docker-client.ts',
  'exec-docker/docker-backend': 'src/exec-docker/docker-backend.ts',
  'exec-docker/remote-docker-cli': 'src/exec-docker/remote-docker-cli.ts',
  'exec-docker/world': 'src/exec-docker/world.ts',
  'exec-docker/fs-provider': 'src/exec-docker/fs-provider.ts',
  'exec-docker/process-provider': 'src/exec-docker/process-provider.ts',
  'exec-docker/provision': 'src/exec-docker/provision.ts',
  'exec-docker/docker-routes': 'src/exec-docker/docker-routes.ts',
  'exec-docker/daemon-runner': 'src/exec-docker/daemon-runner.ts',
  'exec-docker/host-runner': 'src/exec-docker/host-runner.ts',
  'ui/index': 'src/ui/index.ts',
  'ui/decorate-picker': 'src/ui/decorate-picker.ts',
  'ui/picker': 'src/ui/picker.ts',
}

export default defineConfig([
  {
    entry: serverEntries,
    outDir: 'lib',
    format: ['esm'],
    dts: true,
    sourcemap: true,
    clean: true,
    outExtensions: () => ({ js: '.js', dts: '.d.ts' }),
  },
  {
    name: `${BUNDLE_ID}/client`,
    entry: { client: 'src/client/index.tsx' },
    outDir: 'lib',
    format: 'cjs',
    platform: 'browser',
    dts: false,
    sourcemap: true,
    clean: false,
    deps: { neverBundle: EXTERNAL_CLIENT },
    define: { 'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV ?? 'production') },
    outputOptions: {
      entryFileNames: 'client.js',
      banner: `window.__ModuleLoader__.load({ id: ${JSON.stringify(BUNDLE_ID)}, factory: (require) => {`,
      footer: 'return module.exports; } });',
      intro: 'var module = { exports: {} }; var exports = module.exports;',
    },
  },
])
